"""Model-input contract for the ConvNeXt V2 classical three-class engine.

GENERATED by ConvNeXtV2H_Full_Training_Colab.ipynb. Do not edit: the bundle records this
file's SHA-256 and refuses to load if the two disagree.

This module is the inference-side half of the model-input contract. It accepts an
already-prepared export image at the contract resolution, verifies its geometry,
and normalises it once. It deliberately has no resize path and no raw-upload path:

  * resizing at inference would either discard detail or invent it, and would silently
    change the geometry the weights were trained on
  * a raw upload still needs breast cropping and windowing, which the prepared images
    already carry; doing it here would be a second preprocessing pass
  * DICOM is not supported, because no DICOM decoder is implemented or tested

Depends only on numpy and OpenCV. No torch.
"""

import json

import cv2
import numpy as np

BUNDLE_FORMAT = 'convnextv2h-classical-bundle/1'
CONTRACT_HASH = 'a26a0591d4cd3eae61e3c071979f1e8fd4007735db9a7af9d18969fd847b6e6f'
CONTRACT = json.loads('{"version": "model-input/3", "name": "convnextv2h-classical-2048x1024", "model_h": 2048, "model_w": 1024, "channels": 3, "channel_construction": "single grayscale plane replicated to 3 identical channels", "norm_mean": [0.485, 0.456, 0.406], "norm_std": [0.229, 0.224, 0.225], "normalisation": "x/255 then (x - mean) / std, applied exactly once", "geometry_adapter": "passthrough-v2", "geometry_adapter_doc": "verify the decoded prepared image is already model_h x model_w and pass it through unchanged; any other size is a hard error. No resize, no pad, no crop, no upscaling.", "accepts": "prepared prep-v1 export images only, at their native stored resolution", "export_variant": "baseline", "export_variant_doc": "the prepare session writes several variants of every image; this contract consumes exactly one of them, and the others are never extracted", "export_variants_refused": ["clahe"], "refuses": ["raw uploads (breast cropping would be a second preprocessing pass)", "DICOM (no decoder is implemented or tested here)", "any prepared image whose dimensions differ from model_h x model_w", "any export variant other than \'baseline\'"], "class_mapping": {"Normal": 0, "Benign": 1, "Malignant": 2}, "preprocessing_provenance_sha256": "3c2259f535e34c6cbffd1a3a42c63d8bdf1f48f7c8eb7653d9bc75d50673a160", "preprocessing_recorded_target": [2048, 1024], "supersedes": "model-input/1 at 760x456, used by the demo run"}')

MODEL_H = int(CONTRACT["model_h"])
MODEL_W = int(CONTRACT["model_w"])
CHANNELS = int(CONTRACT["channels"])
GEOMETRY_ADAPTER = str(CONTRACT["geometry_adapter"])
NORM_MEAN = np.asarray(CONTRACT["norm_mean"], dtype=np.float32).reshape(CHANNELS, 1, 1)
NORM_STD = np.asarray(CONTRACT["norm_std"], dtype=np.float32).reshape(CHANNELS, 1, 1)
CLASS_NAMES = [name for name, _index in
               sorted(CONTRACT["class_mapping"].items(), key=lambda kv: kv[1])]


class ContractError(ValueError):
    """The input or the bundle does not satisfy the model-input contract."""


def decode(image_bytes):
    """PNG or JPEG bytes to a single grayscale plane at its stored bit depth."""
    if not image_bytes:
        raise ContractError("empty image payload")
    buffer = np.frombuffer(image_bytes, dtype=np.uint8)
    array = cv2.imdecode(buffer, cv2.IMREAD_UNCHANGED)
    if array is None:
        raise ContractError("could not decode the image. PNG and JPEG only; DICOM is not "
                            "supported by this contract")
    if array.ndim == 3:
        planes = [array[:, :, i] for i in range(min(3, array.shape[2]))]
        if all(np.array_equal(planes[0], plane) for plane in planes[1:]):
            return planes[0]
        raise ContractError("genuinely coloured image refused rather than converted; a "
                            "mammogram should be grayscale")
    return array


def adapt_geometry(image):
    """Verify the contract resolution and pass through. There is no resize path."""
    if image.ndim != 2:
        raise ContractError("expected a single-channel image, got shape "
                            + str(image.shape))
    if image.shape != (MODEL_H, MODEL_W):
        raise ContractError("geometry adapter " + GEOMETRY_ADAPTER + " received "
                            + str(image.shape[0]) + "x" + str(image.shape[1])
                            + ", expected " + str(MODEL_H) + "x" + str(MODEL_W)
                            + ". Resizing here would discard or invent detail, so it is "
                            "refused. Prepare the image with the prep-v1 pipeline at the "
                            "contract resolution instead.")
    return image


def normalise(image):
    """Grayscale uint8 to float32 (CHANNELS, H, W), replicated and normalised once."""
    x = image.astype(np.float32) / 255.0
    x = np.repeat(x[None, :, :], CHANNELS, axis=0)
    return (x - NORM_MEAN) / NORM_STD


def prepare_prepared(image_bytes):
    """The only supported entry point: an already-prepared prep-v1 export image."""
    return normalise(adapt_geometry(decode(image_bytes)))


def prepare_raw(image_bytes):
    """Not implemented, on purpose."""
    raise NotImplementedError(
        "raw uploads are not supported by this contract. Breast cropping, windowing and "
        "padding have already been applied to the prepared images; repeating them here "
        "would be a second preprocessing pass and would not reproduce the training "
        "distribution. Run the prep-v1 pipeline first, then call prepare_prepared().")


def calibrated_probabilities(logits, temperature):
    """Softmax of logits divided by the bundle's temperature."""
    z = np.asarray(logits, dtype=np.float64) / float(temperature)
    z = z - z.max(axis=-1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(axis=-1, keepdims=True)


def verify_bundle(bundle):
    """Refuse a bundle whose recorded model-input contract is not the one implemented here."""
    if bundle.get("format") != BUNDLE_FORMAT:
        raise ContractError("bundle format " + str(bundle.get("format"))
                            + " is not " + BUNDLE_FORMAT
                            + ". A bundle trained under a different input geometry must "
                            "not be served through this module.")
    recorded = bundle.get("model_input")
    if recorded is None:
        raise ContractError("bundle records no model_input section")
    if str(recorded.get("hash")) != CONTRACT_HASH:
        raise ContractError("bundle was trained under model-input hash "
                            + str(recorded.get("hash")) + " at "
                            + str(recorded.get("model_h")) + "x"
                            + str(recorded.get("model_w"))
                            + " but this module implements " + CONTRACT_HASH + " at "
                            + str(MODEL_H) + "x" + str(MODEL_W)
                            + ". Serving one through the other would change the input "
                            "geometry silently.")
    if str(bundle.get("preprocessing_provenance", {}).get("module_sha256", "")) == "":
        raise ContractError("bundle records no preprocessing provenance")
    return True
